#!/usr/bin/ruby
primes = []
i = 2
while true do
  lim = Math.sqrt(i).floor
  primep = true
  primes.each { |prime|
    break if prime > lim
    if i % prime == 0 then
      primep = false
      break
    end
  }
  if primep then
    puts i
    primes << i
  end
  i += 1
end

